config/routes.rb
Rails.application.routes.draw do
  resources :lock_requests

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users
  get 'status' => 'status#index'

end

app/models/lock_request.rb
class LockRequest < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, presence: true, uniqueness: true
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	def is_locked
  		# pin = PiPiper::Pin.new(:pin => 11, :direction => :in, :pull => :down)
  		# return pin.value
      Rails.application.config.global_lock
  	end

  	def is_closed
  		# pin = PiPiper::Pin.new(:pin => 13, :direction => :in, :pull => :up)
  		# return pin.value
      true
  	end

    def turn_lock(will_lock)
      if will_lock == true
        #lock the lock
        Rails.application.config.global_lock = true
      else
        #unlock the lock
        Rails.application.config.global_lock = false
      end
    end

  	protected
		def authorize
			unless User.find_by_id(session[:user_id])
			redirect_to login_url, notice: "Please log in" end
		end

end

app/controllers/lock_requests_controller.rb
class LockRequestsController < ApplicationController
  before_action :set_lock_request, only: [:show, :edit, :update, :destroy]
  # GET /lock_requests
  # GET /lock_requests.json
  def index
    @lock_requests = LockRequest.all.reverse
  end

  # GET /lock_requests/1
  # GET /lock_requests/1.json
  def show
  end

  # GET /lock_requests/new
  def new
    @lock_request = LockRequest.new
  end

  # GET /lock_requests/1/edit
  def edit
  end

  # POST /lock_requests
  # POST /lock_requests.json
  def create
    @lock_request = LockRequest.new(lock_request_params)
    #keep history
    @lock_request.user = session[:user_id]
    #check if lock is currently locked
    @lock_request.isLocked = is_locked

    #turn lock
    if is_closed && @lock_request.isLocked != @lock_request.willLock
      turn_lock(@lock_request.willLock)
    end
    respond_to do |format|
      if @lock_request.save
        format.html { redirect_to @lock_request, notice: 'Lock request was successfully created.' }
        format.json { render :show, status: :created, location: @lock_request }
      else
        format.html { render :new }
        format.json { render json: @lock_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lock_requests/1
  # PATCH/PUT /lock_requests/1.json
  def update
    respond_to do |format|
      if @lock_request.update(lock_request_params)
        format.html { redirect_to @lock_request, notice: 'Lock request was successfully updated.' }
        format.json { render :show, status: :ok, location: @lock_request }
      else
        format.html { render :edit }
        format.json { render json: @lock_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lock_requests/1
  # DELETE /lock_requests/1.json
  def destroy
    @lock_request.destroy
    respond_to do |format|
      format.html { redirect_to lock_requests_url, notice: 'Lock request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lock_request
      @lock_request = LockRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lock_request_params
      params.require(:lock_request).permit(:user, :isLocked, :willLock)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :authorize	
	def create
		user = User.find_by_username(params[:username])
		if user and user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to user_path(session[:user_id])
		else
			redirect_to login_url, alert: "Invalid user/password combination"
		end
	end

  
	def destroy
		session[:user_id] = nil
		redirect_to login_url, notice: "Logged out"
	end

	def new
		if session[:user_id]
			redirect_to user_path(session[:user_id])
		end
	end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
	before_filter :authorize
	def index
		@isLocked = is_locked
		@isClosed = is_closed
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password_digest, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lock_requests_helper.rb
module LockRequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoorLock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lock_requests/_form.html.erb
<%= form_for(@lock_request) do |f| %>
  <% if @lock_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lock_request.errors.count, "error") %> prohibited this lock_request from being saved:</h2>

      <ul>
      <% @lock_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :isLocked %><br>
    <%= f.check_box :isLocked %>
  </div>
  <div class="field">
    <%= f.label :willLock %><br>
    <%= f.check_box :willLock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lock_requests/edit.html.erb
<h1>Editing lock_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @lock_request %> |
<%= link_to 'Back', lock_requests_path %>

app/views/lock_requests/index.html.erb
<h1>Listing lock_requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Islocked</th>
      <th>Willlock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lock_requests.each do |lock_request| %>
      <tr>
        <td><%= lock_request.user %></td>
        <td><%= lock_request.isLocked %></td>
        <td><%= lock_request.willLock %></td>
        <td><%= link_to 'Show', lock_request %></td>
        <td><%= link_to 'Edit', edit_lock_request_path(lock_request) %></td>
        <td><%= link_to 'Destroy', lock_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lock request', new_lock_request_path %>

app/views/lock_requests/new.html.erb
<h1>New lock_request</h1>

<%= render 'form' %>

<%= link_to 'Back', lock_requests_path %>

app/views/lock_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @lock_request.user %>
</p>

<p>
  <strong>Islocked:</strong>
  <%= @lock_request.isLocked %>
</p>

<p>
  <strong>Willlock:</strong>
  <%= @lock_request.willLock %>
</p>

<%= link_to 'Edit', edit_lock_request_path(@lock_request) %> |
<%= link_to 'Back', lock_requests_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password, "Password" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation, 'Confirm' %><br>
      <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>